Website/Armsoftech/Armsoftech/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("Main_app.urls")),
]

Website/Armsoftech/Main_app/urls.py
from django.urls import path
from .views import PowerBIDashboardView, SignUp, HomePageView,pythonDashboardView,loading,python_dashput,loading_put
from django.contrib.auth import views as auth_views
from . import views

app_name = 'Main_app'

urlpatterns =[
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('', HomePageView.as_view(), name='home'),
    path('Python_dashboard/', pythonDashboardView.as_view(), name='python_dashboard'),
    path('python_dashboard_put/', python_dashput.as_view(), name='python_dashboard_put'),
    path('loading/', loading.as_view(), name='loading'),
    path('loading_put/', loading_put.as_view(), name='loading_put'),
    path('PowerBI_dashboard/', PowerBIDashboardView.as_view(), name='powerBI_dashboard'),
    path('signup/', SignUp.as_view(), name='signup'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

Website/Armsoftech/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="apple-touch-icon" sizes="76x76" href="/static/img/apple-icon.png">
    <link rel="icon" type="image/png" href="/static/img/favicon.png">
    <title>
    ARMofTech
    </title>
    <!--     Fonts and icons     -->
    <link rel="stylesheet" type="text/css"
        href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,900|Roboto+Slab:400,700" />
    <!-- Nucleo Icons -->
    <!-- Font Awesome Icons -->
    <link href='https://unpkg.com/boxicons@2.0.7/css/boxicons.min.css' rel='stylesheet'>
    <script src="https://kit.fontawesome.com/42d5adcbca.js" crossorigin="anonymous"></script>
    <!-- Material Icons -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons+Round" rel="stylesheet">
    <!-- CSS Files -->
    <link id="pagestyle" href="/static/css/material-dashboard.css" rel="stylesheet" />
    <link id="pagestyle" href="/static/css/sidebar.css" rel="stylesheet" />
    

        <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
</head>

<body style=" background-color: #F0F2F5; ">
    <nav>
        {% block nav %}
            {% include 'navbar.html' %}
        {% endblock %}
    </nav>
    <main>
        {% block Main %}
        {% endblock %}
    </main>
    <footer>
    </footer>
</body>

</html>

Website/Armsoftech/templates/home.html
{% extends "base.html" %}


{% block Main %}
    <div style="display: flex; justify-content: center; align-items: center; height: 100vh; background-color: #F0F2F5;">
        <div>
            {% if request.user.is_authenticated %}
                <h1>HELLO {{user.username}}</h1>
            {% else %}
                <h1>Login</h1>
            {% endif %}
        </div>
    </div>
{%endblock%}

Website/Armsoftech/templates/loading.html
{% extends "base.html" %}

{% block Main %}

<style>
    @charset "UTF-8";
@import url("https://fonts.googleapis.com/css?family=Montserrat:600");
* {

  font-family: "Montserrat", sans-serif;
  box-sizing: border-box;
  animation-timing-function: ease;
}

#BODY {
  display: flex;
  justify-content: center;
  align-items: center;
  height: 100vh;
  background-color: #e3e9f0;
  overflow: hidden;
} 

#wrapper {
  position: relative;
  width: 350px;
  animation: out 0.3s forwards ease;
  animation-delay: 10000s;
  transform: scale(1);
  opacity: 1;
  transform-origin: center -80%;
}
@keyframes out {
  0% {
    transform: scale(1);
    opacity: 1;
  }
  100% {
    transform: scale(0);
    opacity: 0;
  }
}

#wrapper .status {
  margin-top: 10px;
  color: black;
}
#wrapper .status .state {
  float: left;
  font-size: 0.9em;
  letter-spacing: 1pt;
  text-transform: uppercase;
  width: 100px;
  height: 20px;
  position: relative;
}

.loading {
  position: fixed;
  float: left;
  top: 50%;
  left: 50%;
  height: 120px;
  padding: 0px;
  width: 160px;
  margin-top: -50px;
  margin-left: -70px;
  border-left: 1px solid #000000;
  border-bottom: 1px solid #000000;
  padding: 10px;
  box-sizing: border-box;
}

@keyframes loading {
  0% {
    background-color: #cd0a00;
  }
  30% {
    background-color: #fa8a00;
  }
  50% {
    height: 100px;
    margin-top: 0px;
  }
  80% {
    background-color: #91d700;
  }
  100% {
    background-color: #cd0a00;
  }
}
/*@-moz-keyframes loading {
  50% { height: 100px; margin-top: 0px; }
}
@-o-keyframes loading {
  50% { height: 100px; margin-top: 0px; }
}
@keyframes loading {
  50% { height: 100px; margin-top: 0px; }
}*/
.loading .loading-1 {
  height: 10px;
  width: 30px;
  background-color: #fff;
  display: inline-block;
  margin-top: 90px;
  -webkit-animation: loading 2.5s infinite;
  -moz-animation: loading 2.5s infinite;
  -o-animation: loading 2.5s infinite;
  animation: loading 2.5s infinite;
  border-top-left-radius: 2px;
  border-top-right-radius: 2px;
  -webkit-animation-delay: 0.25s;
  animation-delay: 0.25s;
}
.loading .loading-2 {
  height: 10px;
  width: 30px;
  background-color: #fff;
  display: inline-block;
  margin-top: 90px;
  -webkit-animation: loading 2.5s infinite;
  -moz-animation: loading 2.5s infinite;
  -o-animation: loading 2.5s infinite;
  animation: loading 2.5s infinite;
  border-top-left-radius: 2px;
  border-top-right-radius: 2px;
  -webkit-animation-delay: 0.5s;
  animation-delay: 0.5s;
}
.loading .loading-3 {
  height: 10px;
  width: 30px;
  background-color: #fff;
  display: inline-block;
  margin-top: 90px;
  -webkit-animation: loading 2.5s infinite;
  -moz-animation: loading 2.5s infinite;
  -o-animation: loading 2.5s infinite;
  animation: loading 2.5s infinite;
  border-top-left-radius: 2px;
  border-top-right-radius: 2px;
  -webkit-animation-delay: 0.75s;
  animation-delay: 0.75s;
}
.loading .loading-4 {
  height: 10px;
  width: 30px;
  background-color: #fff;
  display: inline-block;
  margin-top: 90px;
  -webkit-animation: loading 2.5s infinite;
  -moz-animation: loading 2.5s infinite;
  -o-animation: loading 2.5s infinite;
  animation: loading 2.5s infinite;
  border-top-left-radius: 2px;
  border-top-right-radius: 2px;
  -webkit-animation-delay: 1s;
  animation-delay: 1s;
}

</style>

<body>
<div id="BODY">
<div id="wrapper">
    <div class="loading">
        <div class="loading-1"></div>
        <div class="loading-2"></div>
        <div class="loading-3"></div>
        <div class="loading-4"></div>
        <div class="status">
            <div class="state"></div>
            <div class="percentage"></div>
        </div>
    </div>
</div>
</div>

<script>
    function getCookie(name) {
            let cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                const cookies = document.cookie.split(';');
                for (let i = 0; i < cookies.length; i++) {
                    const cookie = cookies[i].trim();
                    // Does this cookie string begin with the name we want?
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }
</script>


{% if request.method == 'POST' %}

<script>
    console.log("POST")
    var csrftoken = getCookie('csrftoken');
    $.ajax({
        url: "{% url 'Main_app:loading' %}",
        type: 'POST',
        headers: {
            'X-CSRFToken': csrftoken
        },
        success: function (response_data) {
            console.log(response_data);
            window.location.href = "{% url 'Main_app:python_dashboard' %}";
        },
    });
</script>
 
{% else %}

<script>
  console.log("GET")
   var csrftoken = getCookie('csrftoken');
    $.ajax({
      url: "{% url 'Main_app:loading' %}",
      type: 'GET',
      headers: {
        'X-CSRFToken': csrftoken
      },
      success: function (response_data) {
        window.location.href = "{% url 'Main_app:python_dashboard' %}";
      },
    });
</script>

{% endif %}

{% endblock %}

Website/Armsoftech/templates/loading_put.html
{% extends "base.html" %}

{% block Main %}

<style>
    @charset "UTF-8";
    @import url("https://fonts.googleapis.com/css?family=Montserrat:600");

    * {

        font-family: "Montserrat", sans-serif;
        box-sizing: border-box;
        animation-timing-function: ease;
    }

    #BODY {
        display: flex;
        justify-content: center;
        align-items: center;
        height: 100vh;
        background-color: #e3e9f0;
        overflow: hidden;
    }

    #wrapper {
        position: relative;
        width: 350px;
        animation: out 0.3s forwards ease;
        animation-delay: 10000s;
        transform: scale(1);
        opacity: 1;
        transform-origin: center -80%;
    }

    @keyframes out {
        0% {
            transform: scale(1);
            opacity: 1;
        }

        100% {
            transform: scale(0);
            opacity: 0;
        }
    }

    #wrapper .status {
        margin-top: 10px;
        color: black;
    }

    #wrapper .status .state {
        float: left;
        font-size: 0.9em;
        letter-spacing: 1pt;
        text-transform: uppercase;
        width: 100px;
        height: 20px;
        position: relative;
    }

    .loading {
        position: fixed;
        float: left;
        top: 50%;
        left: 50%;
        height: 120px;
        padding: 0px;
        width: 160px;
        margin-top: -50px;
        margin-left: -70px;
        border-left: 1px solid #000000;
        border-bottom: 1px solid #000000;
        padding: 10px;
        box-sizing: border-box;
    }

    @keyframes loading {
        0% {
            background-color: #cd0a00;
        }

        30% {
            background-color: #fa8a00;
        }

        50% {
            height: 100px;
            margin-top: 0px;
        }

        80% {
            background-color: #91d700;
        }

        100% {
            background-color: #cd0a00;
        }
    }

    /*@-moz-keyframes loading {
  50% { height: 100px; margin-top: 0px; }
}
@-o-keyframes loading {
  50% { height: 100px; margin-top: 0px; }
}
@keyframes loading {
  50% { height: 100px; margin-top: 0px; }
}*/
    .loading .loading-1 {
        height: 10px;
        width: 30px;
        background-color: #fff;
        display: inline-block;
        margin-top: 90px;
        -webkit-animation: loading 2.5s infinite;
        -moz-animation: loading 2.5s infinite;
        -o-animation: loading 2.5s infinite;
        animation: loading 2.5s infinite;
        border-top-left-radius: 2px;
        border-top-right-radius: 2px;
        -webkit-animation-delay: 0.25s;
        animation-delay: 0.25s;
    }

    .loading .loading-2 {
        height: 10px;
        width: 30px;
        background-color: #fff;
        display: inline-block;
        margin-top: 90px;
        -webkit-animation: loading 2.5s infinite;
        -moz-animation: loading 2.5s infinite;
        -o-animation: loading 2.5s infinite;
        animation: loading 2.5s infinite;
        border-top-left-radius: 2px;
        border-top-right-radius: 2px;
        -webkit-animation-delay: 0.5s;
        animation-delay: 0.5s;
    }

    .loading .loading-3 {
        height: 10px;
        width: 30px;
        background-color: #fff;
        display: inline-block;
        margin-top: 90px;
        -webkit-animation: loading 2.5s infinite;
        -moz-animation: loading 2.5s infinite;
        -o-animation: loading 2.5s infinite;
        animation: loading 2.5s infinite;
        border-top-left-radius: 2px;
        border-top-right-radius: 2px;
        -webkit-animation-delay: 0.75s;
        animation-delay: 0.75s;
    }

    .loading .loading-4 {
        height: 10px;
        width: 30px;
        background-color: #fff;
        display: inline-block;
        margin-top: 90px;
        -webkit-animation: loading 2.5s infinite;
        -moz-animation: loading 2.5s infinite;
        -o-animation: loading 2.5s infinite;
        animation: loading 2.5s infinite;
        border-top-left-radius: 2px;
        border-top-right-radius: 2px;
        -webkit-animation-delay: 1s;
        animation-delay: 1s;
    }
</style>

<body>
    <div id="BODY">
        <div id="wrapper">
            <div class="loading">
                <div class="loading-1"></div>
                <div class="loading-2"></div>
                <div class="loading-3"></div>
                <div class="loading-4"></div>
                {% if messages %}
                <ul class="messages">
                    {% for message in messages %}
                    <li{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
                        {% endfor %}
                </ul>
                {% endif %}
            </div>
        </div>
    </div>

    <script>
        function getCookie(name) {
            let cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                const cookies = document.cookie.split(';');
                for (let i = 0; i < cookies.length; i++) {
                    const cookie = cookies[i].trim();
                    // Does this cookie string begin with the name we want?
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }

        console.log("POST")
        var csrftoken = getCookie('csrftoken');
        $.ajax({
            url: "{% url 'Main_app:loading_put' %}",
            type: 'GET',
            headers: {
                'X-CSRFToken': csrftoken
            },
            success: function (response_data) {
                window.location.href = "{% url 'Main_app:python_dashboard_put' %}";
            },
        });
    </script>

    {% endblock %}

Website/Armsoftech/templates/navbar.html
{% if request.user.is_authenticated %}
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                {% if request.user.is_authenticated %}
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'Main_app:home' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'Main_app:powerBI_dashboard' %}">PowerBI Dashboard</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'Main_app:loading' %}">Python Dashboard</a>
                </li>
                {% endif %}
            </ul>
            <span>
                {% if request.user.is_authenticated %}
                <a href="{% url 'Main_app:logout' %}" class="btn" style="position: absolute; top:6.5px; right: 80px; background-color: #4183CD; color: white;">Logout</a>
                {% endif %}
            </span>
        </div>
    </nav>
{% endif %}

Website/Armsoftech/templates/sales_dashboard_using_powerBI.html
{% extends "base.html" %}

{% block Main %}
<div style="display: flex; justify-content: center; align-items: center; height: 100vh;">
    <div style="display: flex; flex-direction: column; justify-content: center; align-items: center;">
        <h1 style="text-align: center; padding-top: 30px;">Sales Dashboard Using PowerBI</h1>
        <iframe title="Sample Report Demo" width="1140" height="600.25"
            src="https://playground.powerbi.com/sampleReportEmbed" frameborder="0"></iframe>
    </div>
</div>
{% endblock %}